const englishQuotes = [
  "Believe in yourself.",
  "Small steps every day lead to big results.",
  "You are capable of amazing things.",
  "Don't wait for opportunity. Create it.",
  "Push yourself, because no one else will.",
  "Dream big. Start small. Act now.",
  "Stay positive, work hard, make it happen.",
  "You’ve got this.",
  "Every day is a fresh start.",
  "Progress, not perfection.",
  "Make today count.",
  "Your only limit is you.",
  "Start where you are. Use what you have. Do what you can.",
  "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
  "Doubt kills more dreams than failure ever will.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Believe you can and you’re halfway there.",
  "Work in silence. Let success make the noise.",
  "Discipline is doing what needs to be done, even if you don’t want to do it.",
  "Don't stop until you're proud.",
  "Strive for progress, not perfection.",
  "One day or day one. You decide.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Difficult roads often lead to beautiful destinations.",
  "If it doesn’t challenge you, it won’t change you.",
  "Winners are not people who never fail, but people who never quit.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Success is what comes after you stop making excuses.",
  "Push yourself because no one else is going to do it for you.",
  "The secret of getting ahead is getting started.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don't watch the clock; do what it does. Keep going.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Great things never come from comfort zones.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Do something today that your future self will thank you for.",
  "Don’t limit your challenges. Challenge your limits.",
  "Dream it. Wish it. Do it.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The key to success is to focus on goals, not obstacles.",
  "Little things make big days.",
  "You are stronger than you think.",
  "Nothing worth having comes easy.",
  "Go the extra mile. It’s never crowded.",
  "A little progress each day adds up to big results.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "The only way to do great work is to love what you do.",
  "Set goals. Stay quiet about them. Smash the hell out of them. Clap for your damn self.",
  "Don’t wait for inspiration. Be the inspiration.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Your journey is your strength.",
  "There is no failure, only feedback.",
  "Energy and persistence conquer all things.",
  "You’re doing better than you think.",
  "Don’t give up. Great things take time.",
  "You are your only competition.",
  "Stop doubting yourself, work hard, and make it happen.",
  "Don't downgrade your dream just to fit your reality. Upgrade your belief to match your vision.",
  "Stay consistent, even when it’s hard.",
  "Success starts with self-discipline.",
  "Great minds discuss ideas. Average minds discuss events. Small minds discuss people.",
  "A goal without a plan is just a wish.",
  "Make yourself proud.",
  "Your comfort zone will destroy you.",
  "Sometimes the smallest step in the right direction ends up being the biggest step of your life.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
  "Every accomplishment starts with the decision to try.",
  "If opportunity doesn't knock, build a door.",
  "Don’t let yesterday take up too much of today.",
  "Success is not in what you have, but who you are.",
  "Start now. Not tomorrow.",
  "The future depends on what you do today.",
  "Winners focus on winning. Losers focus on winners.",
  "Get up. Dress up. Show up. Never give up.",
  "Be stronger than your excuses.",
  "Be so good they can’t ignore you.",
  "Don’t fear failure. Fear being in the exact same place next year.",
  "If you get tired, learn to rest, not to quit.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "One step at a time is progress.",
  "Be the hardest worker in the room.",
  "Success doesn’t rush. The greatest reward is the journey.",
  "Hustle in silence and let your success make the noise.",
  "Sometimes later becomes never. Do it now.",
  "Don’t count the days, make the days count.",
  "Winners never quit and quitters never win.",
  "Perseverance is not a long race; it's many short races one after the other.",
  "Success isn’t overnight. It’s when every day you get a little better than the day before.",
  "Stay focused and never give up.",
  "Your dreams don’t work unless you do.",
  "The way to get started is to quit talking and begin doing.",
  "Be afraid and do it anyway.",
  "If you want to fly, you have to give up the things that weigh you down.",
  "You were born to be real, not perfect.",
  "Mistakes are proof that you are trying.",
  "Don’t compare your chapter 1 to someone else’s chapter 20.",
  "Your vibe attracts your tribe.",
  "You only fail when you stop trying.",
  "Never stop learning, because life never stops teaching.",
  "Failure is the opportunity to begin again, more intelligently.",
  "Fall seven times, stand up eight.",
  "The expert in anything was once a beginner.",
  "Great things take time. Be patient.",
  "Don’t just exist. Live.",
  "Never regret a day in your life. Good days give happiness, bad days give experience.",
  "Success doesn’t come to you. You go to it.",
  "The best view comes after the hardest climb.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Act as if what you do makes a difference. It does.",
  "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, I will try again tomorrow.",
  "Do not wait for the perfect time, take the time and make it perfect.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice, and most of all, love of what you are doing.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "It always seems impossible until it’s done.",
  "Don’t tell people your plans. Show them your results.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Don't wait. The time will never be just right.",
  "There is no elevator to success — you have to take the stairs.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Action is the foundational key to all success.",
  "You don't find willpower, you create it.",
  "Opportunities don't happen. You create them.",
  "Don’t be pushed by your problems. Be led by your dreams.",
  "If you can dream it, you can do it.",
  "If you want it, work for it. It's that simple.",
  "Work while they sleep. Learn while they party. Save while they spend. Live like they dream.",
  "No pressure, no diamonds.",
  "Don’t let your fear decide your future.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Focus on being productive instead of busy.",
  "Work hard in silence, let success be your noise.",
  "One day, all your hard work will pay off.",
  "Champions keep playing until they get it right.",
  "Great work is done by people who are not afraid to be great.",
  "Ambition is the first step to success. The second is action.",
  "Learn as if you will live forever, live like you will die tomorrow.",
  "You can't cross the sea merely by standing and staring at the water.",
  "A winner is just a loser who tried one more time.",
  "Failure is not the opposite of success; it’s part of success.",
  "Success doesn't just find you. You have to go out and get it.",
  "You're closer than you think.",
  "Start where you are. Use what you have. Do what you can.",
  "Consistency is more important than perfection.",
  "Never let the fear of striking out keep you from playing the game.",
  "If you don’t build your dream, someone else will hire you to help them build theirs.",
  "Stars can’t shine without darkness.",
  "Be a voice, not an echo.",
  "Let your hustle be louder than your mouth.",
  "Success is the best revenge.",
  "You were not born to just pay bills and die.",
  "Always do your best. What you plant now, you will harvest later.",
  "If you believe it will work out, you’ll see opportunities. If you believe it won’t, you’ll see obstacles.",
  "Be willing to be a beginner every single morning.",
  "Chase your dreams, but always know the road that will lead you home again.",
    "Believe in yourself.",
  "Small steps every day lead to big results.",
  "You are capable of amazing things.",
  "Don't wait for opportunity. Create it.",
  "Push yourself, because no one else will.",
  "Dream big. Start small. Act now.",
  "Stay positive, work hard, make it happen.",
  "You’ve got this.",
  "Every day is a fresh start.",
  "Progress, not perfection.",
  "Make today count.",
  "Your only limit is you.",
  "Start where you are. Use what you have. Do what you can.",
  "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
  "Doubt kills more dreams than failure ever will.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Believe you can and you’re halfway there.",
  "Work in silence. Let success make the noise.",
  "Discipline is doing what needs to be done, even if you don’t want to do it.",
  "Don't stop until you're proud.",
  "Strive for progress, not perfection.",
  "One day or day one. You decide.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Difficult roads often lead to beautiful destinations.",
  "If it doesn’t challenge you, it won’t change you.",
  "Winners are not people who never fail, but people who never quit.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Success is what comes after you stop making excuses.",
  "Push yourself because no one else is going to do it for you.",
  "The secret of getting ahead is getting started.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don't watch the clock; do what it does. Keep going.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Great things never come from comfort zones.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Do something today that your future self will thank you for.",
  "Don’t limit your challenges. Challenge your limits.",
  "Dream it. Wish it. Do it.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The key to success is to focus on goals, not obstacles.",
  "Little things make big days.",
  "You are stronger than you think.",
  "Nothing worth having comes easy.",
  "Go the extra mile. It’s never crowded.",
  "A little progress each day adds up to big results.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "The only way to do great work is to love what you do.",
  "Set goals. Stay quiet about them. Smash the hell out of them. Clap for your damn self.",
  "Don’t wait for inspiration. Be the inspiration.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway."
];
const urduQuotes = [
      "اپنے آپ پر یقین رکھو۔",
      "ہر دن کا ایک چھوٹا قدم بڑے نتائج لاتا ہے۔",
      "آپ حیرت انگیز کام کرنے کی صلاحیت رکھتے ہیں۔",
      "موقع کا انتظار نہ کرو، خود بناؤ۔",
      "خود کو آگے بڑھاؤ، کوئی اور نہیں کرے گا۔",
      "بڑے خواب دیکھو، چھوٹے اقدامات سے شروع کرو۔",
      "مثبت سوچو، محنت کرو، کامیابی حاصل کرو۔",
      "آپ یہ کر سکتے ہیں!",
      "کمال نہیں، ترقی ضروری ہے۔",
      "آپ کی واحد حد آپ خود ہیں۔"
    ];



   
    function showQuote(language) {
      const quoteList = language === 'english' ? englishQuotes : urduQuotes;
      const randomIndex = Math.floor(Math.random() * quoteList.length);
      document.getElementById("quoteDisplay").textContent = quoteList[randomIndex];
    }